language: dart

dart:
  - '2.4.1' # TODO: Remove this and bump the lower SDK bound to 2.6.0 once released.
  - stable
  - dev

before_script:
  - pub run build_runner build --delete-conflicting-outputs
  - git diff --exit-code
  - pub run dart_dev analyze
  - pub run dependency_validator -i test_html_builder

script:
  - pub run dart_dev test
  - pub run dart_dev test --release -P dart2js

cache:
  directories:
   - $HOME/.pub-cache
   - $HOME/.dart_tool/build
