builders:
  overReactBuilder:
    import: "package:over_react/builder.dart"
    builder_factories: ["overReactBuilder"]
    build_extensions: {".dart" : [".over_react.g.dart"]}
    auto_apply: dependents
    build_to: cache

  # Builder just for this package.
  _over_react_local_builder:
    import: "lib/builder.dart"
    builder_factories: ["overReactBuilder"]
    build_extensions: {".dart" : [".over_react.g.dart"]}
    auto_apply: none
    build_to: source

targets:
  $default:
    builders:
      over_react|_over_react_local_builder:
        enabled: true
        generate_for:
          exclude:
            # This tests un-built behavior, and therefore should not be built
            - "test/over_react/component_declaration/builder_helpers_test.dart"

      over_react|overReactBuilder:
        enabled: false

      build_vm_compilers|entrypoint:
        generate_for:
          include:
            - "test/vm_tests/**.vm_test.dart"

      test_html_builder:
        options:
          templates:
            "test/html_test_template.html":
              - "test/over_react/**_test.dart"
              - "test/over_react_redux/**_test.dart"
